export {default as RecDashboard} from "./RecDetails"
export {default as RecProfile} from "./RecProfile"
export {default as ManagedJobs} from "./ManagedJobs"
export {default as Applications} from "./Applications"
export {default as RecMessage} from "./RecMessage"
export {default as RecPostJobs} from "./PostNewJobs"
export {default as CompanyPage} from "./CompanyPage"