name: Node.js CI

on:
  push:
    branches: [master]
  

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node-version}}
    - run: |

        cd client
        npm i
        npm run build
        cp -r build/* /var/www/cryptojobs/_work/cryptojoblist/cryptojoblist
        cd ../server
        npm i
        pm2 startup 